apiVersion: v1
kind: Pod
metadata:
  namespace: treinamento-ch2
  labels:
    desafio: day2
  name: pod-faminto
spec:
  containers:
  - image: polinux/stress
    name: pod-faminto
    command: ["stress", "--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "0.5"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
