apiVersion: v1
kind: Pod
metadata:
  namespace: treinamento-ch2
  name: pod-comportado
spec:
  containers:
  - image: polinux/stress
    name: pod-comportado
    command: ["stress", "--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "300Mi"
        cpu: "1"
      requests:
        memory: "250Mi"
        cpu: "0.5"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
