apiVersion: v1
kind: Pod
metadata:
  name: pod-com-secret
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: USERNAME  
          valueFrom:
            secretKeyRef:
              name: primeiro-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: primeiro-secret
              key: password